version: '2.1'
services:
  proxy:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - academy-api
    ports:
      - 80:80
  academy-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      STUDENTS_URL: '192.168.99.102'
      STUDENTS_PORT: '4000'
      STUDENTS_ENTRY: 'students/'
      COURSES_URL: '192.168.99.102'
      COURSES_PORT: '4001'
      COURSES_ENTRY: 'courses/'
      GRADES_URL: '192.168.99.102'
      GRADES_PORT: '4002'
      GRADES_ENTRY: 'grades/'